server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**


  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 166306284810-hg05dsabt83cg761qdmnnrio61098lg4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: Dy59R36wQ0pUJ7k9o1__
            clientSecret: 1RElDJSMFY
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-study.cvyhp6qkgzwg.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1q2w3e4r!


mybatis:
  mapper-locations:
    - /mappers/*.xml